using WebFileBrowser.Models;

namespace WebFileBrowser.Services.ObjectDetection;

public class YoloCocoObjectDetector : OnnxObjectDetector {

    public YoloCocoObjectDetector(ILogger<YoloCocoObjectDetector> logger) : base(
        "onnx/yolo26s-coco.onnx",
        new Dictionary<int, LabelClass>{
            [0] = new LabelClass("person", DetectedObjectClass.Person),
            [1] = new LabelClass("bicycle", DetectedObjectClass.Unknown),
            [2] = new LabelClass("car", DetectedObjectClass.Unknown),
            [3] = new LabelClass("motorcycle", DetectedObjectClass.Unknown),
            [4] = new LabelClass("airplane", DetectedObjectClass.Unknown),
            [5] = new LabelClass("bus", DetectedObjectClass.Unknown),
            [6] = new LabelClass("train", DetectedObjectClass.Unknown),
            [7] = new LabelClass("truck", DetectedObjectClass.Unknown),
            [8] = new LabelClass("boat", DetectedObjectClass.Unknown),
            [9] = new LabelClass("traffic light", DetectedObjectClass.Unknown),
            [10] = new LabelClass("fire hydrant", DetectedObjectClass.Unknown),
            [11] = new LabelClass("stop sign", DetectedObjectClass.Unknown),
            [12] = new LabelClass("parking meter", DetectedObjectClass.Unknown),
            [13] = new LabelClass("bench", DetectedObjectClass.Furniture),
            [14] = new LabelClass("bird", DetectedObjectClass.Animal),
            [15] = new LabelClass("cat", DetectedObjectClass.Animal),
            [16] = new LabelClass("dog", DetectedObjectClass.Animal),
            [17] = new LabelClass("horse", DetectedObjectClass.Animal),
            [18] = new LabelClass("sheep", DetectedObjectClass.Animal),
            [19] = new LabelClass("cow", DetectedObjectClass.Animal),
            [20] = new LabelClass("elephant", DetectedObjectClass.Animal),
            [21] = new LabelClass("bear", DetectedObjectClass.Animal),
            [22] = new LabelClass("zebra", DetectedObjectClass.Animal),
            [23] = new LabelClass("giraffe", DetectedObjectClass.Animal),
            [24] = new LabelClass("backpack", DetectedObjectClass.Unknown),
            [25] = new LabelClass("umbrella", DetectedObjectClass.Unknown),
            [26] = new LabelClass("handbag", DetectedObjectClass.Unknown),
            [27] = new LabelClass("tie", DetectedObjectClass.Unknown),
            [28] = new LabelClass("suitcase", DetectedObjectClass.Unknown),
            [29] = new LabelClass("frisbee", DetectedObjectClass.Unknown),
            [30] = new LabelClass("skis", DetectedObjectClass.Unknown),
            [31] = new LabelClass("snowboard", DetectedObjectClass.Unknown),
            [32] = new LabelClass("sports ball", DetectedObjectClass.Unknown),
            [33] = new LabelClass("kite", DetectedObjectClass.Unknown),
            [34] = new LabelClass("baseball bat", DetectedObjectClass.Unknown),
            [35] = new LabelClass("baseball glove", DetectedObjectClass.Unknown),
            [36] = new LabelClass("skateboard", DetectedObjectClass.Unknown),
            [37] = new LabelClass("surfboard", DetectedObjectClass.Unknown),
            [38] = new LabelClass("tennis racket", DetectedObjectClass.Unknown),
            [39] = new LabelClass("bottle", DetectedObjectClass.Unknown),
            [40] = new LabelClass("wine glass", DetectedObjectClass.Unknown),
            [41] = new LabelClass("cup", DetectedObjectClass.Unknown),
            [42] = new LabelClass("fork", DetectedObjectClass.Unknown),
            [43] = new LabelClass("knife", DetectedObjectClass.Unknown),
            [44] = new LabelClass("spoon", DetectedObjectClass.Unknown),
            [45] = new LabelClass("bowl", DetectedObjectClass.Unknown),
            [46] = new LabelClass("banana", DetectedObjectClass.Unknown),
            [47] = new LabelClass("apple", DetectedObjectClass.Unknown),
            [48] = new LabelClass("sandwich", DetectedObjectClass.Unknown),
            [49] = new LabelClass("orange", DetectedObjectClass.Unknown),
            [50] = new LabelClass("broccoli", DetectedObjectClass.Unknown),
            [51] = new LabelClass("carrot", DetectedObjectClass.Unknown),
            [52] = new LabelClass("hot dog", DetectedObjectClass.Unknown),
            [53] = new LabelClass("pizza", DetectedObjectClass.Unknown),
            [54] = new LabelClass("donut", DetectedObjectClass.Unknown),
            [55] = new LabelClass("cake", DetectedObjectClass.Unknown),
            [56] = new LabelClass("chair", DetectedObjectClass.Furniture),
            [57] = new LabelClass("couch", DetectedObjectClass.Furniture),
            [58] = new LabelClass("potted plant", DetectedObjectClass.Unknown),
            [59] = new LabelClass("bed", DetectedObjectClass.Furniture),
            [60] = new LabelClass("dining table", DetectedObjectClass.Unknown),
            [61] = new LabelClass("toilet", DetectedObjectClass.Unknown),
            [62] = new LabelClass("tv", DetectedObjectClass.Unknown),
            [63] = new LabelClass("laptop", DetectedObjectClass.Unknown),
            [64] = new LabelClass("mouse", DetectedObjectClass.Unknown),
            [65] = new LabelClass("remote", DetectedObjectClass.Unknown),
            [66] = new LabelClass("keyboard", DetectedObjectClass.Unknown),
            [67] = new LabelClass("cell phone", DetectedObjectClass.Unknown),
            [68] = new LabelClass("microwave", DetectedObjectClass.Unknown),
            [69] = new LabelClass("oven", DetectedObjectClass.Unknown),
            [70] = new LabelClass("toaster", DetectedObjectClass.Unknown),
            [71] = new LabelClass("sink", DetectedObjectClass.Unknown),
            [72] = new LabelClass("refrigerator", DetectedObjectClass.Unknown),
            [73] = new LabelClass("book", DetectedObjectClass.Unknown),
            [74] = new LabelClass("clock", DetectedObjectClass.Unknown),
            [75] = new LabelClass("vase", DetectedObjectClass.Unknown),
            [76] = new LabelClass("scissors", DetectedObjectClass.Unknown),
            [77] = new LabelClass("teddy bear", DetectedObjectClass.Unknown),
            [78] = new LabelClass("hair drier", DetectedObjectClass.Unknown),
            [79] = new LabelClass("toothbrush", DetectedObjectClass.Unknown)
        },
        logger
    ){}
}